### ISSUE TITLE
Consider using Podman Desktop builds from testing-prereleases instead of building podman-desktop

### ISSUE THREAD

**Issue by odockal** [podman-desktop/extension-podman-quadlet#422]
We have testing-prereleases available (that have `ELECTRON_ENABLE_INSPECT` flag set for playwright to connect to it) at https://github.com/podman-desktop/testing-prereleases.

They can be used to download particular installer (ie. setup-exe) of podman-desktop instead of reusing podman-desktop repo and building it for the tests.

Here is how:
1. download the setup.exe installer (maybe you can also cache it for other builds)
2. Install it locally on the machine (it has hardcoded path where it is installed - https://github.com/odockal/pde2e-runner/blob/main/lib/windows/runner.ps1#L432-L449)
3. Get the path to the `Podman Desktop.exe` and save it to the gh env var.
```
echo "PODMAN_DESKTOP_BINARY_PATH=$path" >> $GITHUB_ENV
```
4. You can now run the e2e tests from quadlet repo using ie.:
```
      - name: Run All E2E tests
        working-directory: ./podman-desktop-redhat-account-ext
        env:
          PODMAN_DESKTOP_BINARY: ${{ env.PODMAN_DESKTOP_BINARY_PATH }}
        run: |
          pnpm test:e2e
```
